### ISSUE TITLE
Improve class design theory

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#38]
- aggregation and composition are two different things with two different types of arrow. In the course, we use composition
- the example diagram does not make sense:

```mermaid
classDiagram
    Move *-- set_speed
    Move *-- set_direction
    Move *-- change_position
```

This suggests that a `Move` object is composed of a `set_speed`, `set_direction` and `change_position` object

```mermaid
classDiagram
  class Person{
    + name
    + personnummer
  }
```

or

```mermaid
classDiagram
  note "Not all strings are names"
  class Name{
    + name
    + set_name(str)
    + get_number()
  }
```

or

```mermaid
classDiagram
  note "Not all strings are names\nNot all numbers are personnummers"

  class Person{
    + name
    + personnummer
  }
  class Name{
    + name
    + set_name(str)
    + get_number()
  }
  class Personnummer{
    + number
    + set_number(int)
    + get_number()
  }
  Person *-- Name
  Person *-- Personnummer
```

**Comment by LarsEklund** [comment]
Valid point the chosen example was written as a response to learners creation of behavior, and is using the class diagram instead of the object diagram that was under consideration a better diagram here is to use the flowchart TD diagram as not to confuse it with a class or true object. but rather to show that a behavior could be nested by and broken down into simpler behaviors which compose the more complex behavior as to preserve one function one result and showing how one can partition the behavior into smaller part. Needs to be moved and clarified in the text.

**Comment by richelbilderbeek** [comment]
Great! I took the liberty to assign you this Issue :-)
