### ISSUE TITLE
Record lectures responsibly

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/programming_formalisms#62]
I miss having a video of lectures I teach for own private usage,
such as making activity diagrams (see below)
I can do a screen recording from my own computer and keep it someplace
private. How to do this responsibly?

**Comment by richelbilderbeek** [comment]
This was discussed at [2024-10-10's meeting](https://github.com/UPPMAX/programming_formalisms/blob/main/meeting_notes/20241010.md) and @LarsEklund will find out how :+1:

**Comment by richelbilderbeek** [comment]
From Lars: we are only allowed to record without consent.

**Comment by LarsEklund** [comment]
Recording persons and responses are always tricky if done wo consent, also since you would be recording as a representative for an instution and it would be done systematically, and etnicity would be vislble the data would be considered sensitive. Unless you pass the recording through a filter to filter out the participants video. the voice recording would in general not be sensitive in this context. One could argue that recording and storing responsible with post information and consent after data is collected could be a way of making sure that the data is not biased from the people knowing, but then it would probably land in the realm of research and need ethical approval and the whole shebang.

**Comment by LarsEklund** [comment]
There seems to be a general consensus among lawyers that if a student records for their personal use no consent or information are needed, but as a lecturer as I described above One needs to have prior consent and a legal bases for the recording, that means that the recording needs to have a legitament reason.  as mentioned above

**Comment by richelbilderbeek** [comment]
Thanks @LarsEklund, seems like a human observer is the old-skool way to go :+1:
